### PR TITLE
Update to COLMAP HEAD

### PR DESCRIPTION
**Pull request by sarlinpe**
Update to https://github.com/colmap/colmap/commit/3254263266949413d7c669e44abeb4a7c2670a8b. I don't know how you want to handle older versions of COLMAP - maybe by creating a new release? Merging this into the COLMAP repos would definitely make this easier.

### CODE REVIEW

**Comment by ahojnnes** [comment]
Eventually, we should introduce a global_mapper option into colmap. This indeed becomes difficult to maintain in the long-term. Meanwhile, I don't think there is an ambition to support multiple versions of colmap. The only use case for not using the FetchContent approach is when one wants to make code changes to both glomap and colmap at the same time.

**Comment by B1ueber2y** [comment]
The intention of this update was to support in glomap the newly introduced camera model (https://github.com/colmap/colmap/pull/2786) and updated undistortion (https://github.com/colmap/colmap/pull/2857) for Fisheye images. This workflow may need to be gone through repeatedly in the future when the base classes are updated.

**Review by ahojnnes — APPROVED** [review]

**Comment by ahojnnes** [comment]
Thanks very much @sarlinpe !

**Comment by lpanaf** [comment]
Sorry but I just have time to look into it. Thank you so much @sarlinpe !

**Pull request merged**
